export const FETCHING_ERROR = 'FETCHING_ERROR';
export const IS_LOADING = 'IS_LOADING';
export const GET_ALL_TEMPLATES = 'GET_ALL_TEMPLATES';
export const GET_TEMPLATE = 'GET_TEMPLATE';
export const SAVE_TEMPLATE = 'SAVE_TEMPLATE';
export const EDIT_TEMPLATE = 'EDIT_TEMPLATE';
export const DELETE_TEMPLATE = 'DELETE_TEMPLATE';
export const FILTER_TEMPLATE = 'FILTER_TEMPLATE';
